### ISSUE TITLE
Update docs for browser usage

### ISSUE THREAD

**Issue by dav-leda** [Mister-Hope/bcrypt-ts#209]
First off, thank you so much for creating bcrypt-ts 🙂️ 

I was trying to run it on the browser (using Vite as bundler) without success until I noticed there's an oversight in the docs:

*If you meet any issues that a incorrect bundle is used, you can use bcrypt-ts/node and bcrypt-ts/client to force the correct bundle.*

For browser usage, it's __brcrypt-ts/browser__ not __client__

**Comment by Mister-Hope** [comment]
Thanks for pointing out, could you kindly open a apr to fix that in README?

**Comment by Mister-Hope** [comment]
https://github.com/Mister-Hope/bcrypt-ts/commit/527c2ab20a0b41ae857dfcdf23b051757d7fc1fd
