### ISSUE TITLE
Cannot find module 'bcrypt-ts/node' or its corresponding type declarations.

### ISSUE THREAD

**Issue by deanc** [Mister-Hope/bcrypt-ts#211]
I get issues when importing this module in our jest environment (`import { hashSync } from 'bcrypt-ts'`). So as suggested in the README I switched to `import { hashSync } from 'bcrypt-ts/node'` and while that fixes things to work correctly when running our tests we get errors in vscode that I cannot resolve:

`Cannot find module 'bcrypt-ts/node' or its corresponding type declarations.`

Any ideas?

This was a workaround in our repo (to get the tests to run when using `import { hashSync } from 'bcrypt-ts'`) but I'd prefer not to have to hardcode these things in jest config (we are using yarn workspaces in a monorepo):
```
  moduleNameMapper: {
    'bcrypt-ts': '<rootDir>/../../node_modules/bcrypt-ts/dist/node.cjs',
  },
```

I guess the reason this works is because jest sees an `import` which you have mapped to an mjs file, not cjs file.

**Comment by Mister-Hope** [comment]
I think that your tsconfig may be inccorect. To use es module path exports, you have to set `moduleResolution` to `NodeNext` or `Bundler`

**Comment by deanc** [comment]
Is there no way to explicitly import it as a commonjs module? When changing this tsconfig it causes all kinds of headaches and issues across the codebase currently.

**Comment by Mister-Hope** [comment]
maybe changing nodenext to bundler?

**Comment by Mister-Hope** [comment]
Now typescript will give you correct error telling you module should be nodenext when moduleResolution is nodenext, so I think there is no more issues here.

With the correct tsconfig, everything should work.
