### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by rppala3** [Mister-Hope/bcrypt-ts#344]
version "bcrypt-ts": "5.0.2"

### Steps To Reproduce

Run the code below 
````
import { hashSync } from "bcrypt-ts";
const defaultPassword = 'secret'
const digest = hashSync(defaultPassword);
````
using one of the following commands `node -r esbuild-register ./script.ts` or `ts-node ./script.ts`

### The current behavior

Facing with this error in the console
````
SyntaxError: Cannot use import statement outside a module
````

### Workaround

Don't trust the editor autocomplete and import manually the library below
````
import { hashSync } from "bcrypt-ts/node";
````

**Comment by Mister-Hope** [comment]
I don't think this is a bug related to package,  I believe I am using the correct conditional.exports in package JSON

**Comment by Mister-Hope** [comment]
Oh wait. The default might need to be `.mjs`,  You can confirm that  by manually editing the local package,  And see if that works

**Comment by Mister-Hope** [comment]
I think I can not fix by my side for this. At least the node sub export works.

**Comment by panalgin** [comment]
I think the default for the node should be "./dist/node.cjs", that's how I could resolve the issue with my NestJS backend, which uses CommonJS

**Comment by foxbit19** [comment]
Hi @panalgin, did you resolve the issue?

**Comment by panalgin** [comment]
I could resolve it for my case by editing package.json manually and changing node.mjs to node.cjs @foxbit19

**Comment by foxbit19** [comment]
Thanks @panalgin.
I delved deeper into this issue and was able to solve it by using the `NodeNext` setting in `tsconfig.json`.
```json
{
    "module": "NodeNext",
    "moduleResolution": "NodeNext"
}
```

I've also use dynamic import for the library.

```ts
const bcrypt = await import('bcrypt-ts');
const salt = bcrypt.genSaltSync(10);
return bcrypt.hashSync(password, salt);
```

Maybe @Mister-Hope can confirm this is the correct way to use this library.

**Comment by Mister-Hope** [comment]
I am not sure, maybe the node condition export should be removed?
