### ISSUE TITLE
Anyway to remove the Buffer type so it is compatible with cloudflare workers?

### ISSUE THREAD

**Issue by tokenhousetopdev** [Mister-Hope/bcrypt-ts#39]
When running tsc I get this error:

```
node_modules/bcrypt-ts/dist/node.d.mts:7:52 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

7 declare const encodeBase64: (byteArray: number[] | Buffer, length: number) => string;
```

I don't want to install node type definitions because I am using this in cloudflare workers which doesn't support node.

I am using typescript for the first time so I am not aware on the best way to solve this issue, maybe I can't use this library?

**Comment by Mister-Hope** [comment]
If you are running on node, then `@types/node` is expected to be installed if you are using typescript.

If you are running on client, you can use `bcrypt-ts/client` with No issue if you add `DOM` to `lib` in tsconfig.json

**Comment by Mister-Hope** [comment]
I publish v3.0.0 and stop exporting encode/decode base64 apis, however I am not sure this will solve your problem.

Bcrypt need a random function, and we use `node:crypto` module at node and `window.crypto` (or `window.msCrypto` with old edge) at browers. If none of these apis exisit in your "cloudflare workers", then probably the package won't work for you.
